### ISSUE TITLE
Extract non Quest specific components into generalized VR Toolkit

### ISSUE THREAD

**Issue by Wavesonics** [NeoSpark314/godot_oculus_quest_toolkit#11]
It would be pretty nice to have two seperate projects here.
1) VR Toolkit
This would contain things like the Buttons, UiCanvas, lots of other things that are just solutions to general VR problems

2) Quest toolkit
This would contain the Quest specific utilities, setup, model, ect.

I think lots of VR projects will want to use support both Quest and PC VR. Seperating these out would allow anyone to use the VR Toolkit.

**Comment by NeoSpark314** [comment]
The toolkit already supports using PCVR together with the Quest (or only PCVR). You can add the respective PCVR addon and the initialization already checks if they are available. So I don't see a need to split it.
And there is also the https://github.com/GodotVR/godot-vr-common project that has as a goal to be a cross platform VR toolkit.

**Comment by Wavesonics** [comment]
ah you're right, never mind then!

**Comment by NeoSpark314** [comment]
If you try to use the toolkit and run into problems let me know.

**Comment by Wavesonics** [comment]
Thanks @NeoSpark314 this toolkit is such a time saving its incredible!
