### ISSUE TITLE
vr not found

### ISSUE THREAD

**Issue by ssj71** [NeoSpark314/godot_oculus_quest_toolkit#12]
First, thanks for doing this project, it's a really great idea!

Sorry if I'm doing something very dumb, I'm still new to godot and game dev in general. I installed the toolkit through the assets store, set the GameMain.tscn as the main scene and drag demo_scenes/GodotSplash.tscn as a child node to the root as the main scene. When I click the play button to run the game it just errors in GameMain.gd at the first reference to the vr object `vr.button_just_released()...`. I don't quite get how this vr object is supposed to be created or inherited from. 

This is on godot 3.2.1 on macOS. Happy to provide additional details. I see the wiki is a WIP, I'd be happy to pitch in there a little more once I figure it out myself.

**Comment by ssj71** [comment]
DOH! I think it's answered on this page: https://github.com/NeoSpark314/godot_oculus_quest_toolkit/wiki/Overview-of-Features lemme try it

**Comment by ssj71** [comment]
yeah, sorry for the noise. I'll try to RTFM better. :\ Thanks again for making this!

**Comment by NeoSpark314** [comment]
Hi, no problem; feel free to contact me for any other problem you run into. Thanks for trying out the toolkit! You can also reach me in the official godot discord #XR channel or directly on discord via NeoSpark314#4701
