### ISSUE TITLE
new early project for showcase.

### ISSUE THREAD

**Issue by Plopsiskopsis** [NeoSpark314/godot_oculus_quest_toolkit#13]
Making a simple western style low poly shooter. My first VR project. 
![org godotengine vr-20200318-173639](https://user-images.githubusercontent.com/35765659/78772960-338d2000-799b-11ea-9479-fd59840f3f73.jpg)

**Comment by NeoSpark314** [comment]
Nice; Do you have a link to a landing/project page that I can link to with the picture when I include it?

**Comment by Plopsiskopsis** [comment]
Not yet. Need to add some more stuff still to this. Will let you know once that is available.

**Comment by NeoSpark314** [comment]
Hi, do you have a project page or video now that I could link to?

**Comment by Plopsiskopsis** [comment]
Nothing more than https://twitter.com/Plopsis1/status/1248305905055170560?s=20

I haven't been on my dev computer for some time.

**Comment by Wavesonics** [comment]
Here's my game for a show case entry: https://wavesonics.itch.io/fugitive-3d

**Comment by NeoSpark314** [comment]
Thanks @Wavesonics; I added it to the showcases; at the moment it is only in the experimental branch; but I will merge it soon into master
