### ISSUE TITLE
The hand model is missing

### ISSUE THREAD

**Issue by Jiankors** [NeoSpark314/godot_oculus_quest_toolkit#15]
Great job
And we deploy the toolkit successfully, thanks. But the hand model were missing in the hand track demo scene, who can help to solve this issue?

**Comment by NeoSpark314** [comment]
Did you activate hand tracking? They only appear when hand tracking is active on the Quest.

**Comment by Jiankors** [comment]
Thanks for your response.
I have actived hand tracking, and tracking result displayed correctly on the label. So, what can i do next to make this sample work? THX.

**Comment by NeoSpark314** [comment]
Can you explain a bit more about the problem. I'm not sure I understand it correctly. Does handtracking work outside of the demo application in the Oculus Quest Main menu (and do you see the oculus hand models there?); If you have hand tracking active the hand models should show in all demo applications not only the hand tracking gesture detection demo.

**Comment by Jiankors** [comment]
Yes, hand tracking work well outside of the demo application, and i can see the hand model  in the Oculus Quest default scene.
Once enter the demo appllication, the hand model is missing in all demo scene, but i can still see the tracking result on the label.
THX.

**Comment by NeoSpark314** [comment]
The hand model should be located in this folder (.gltf models for the left and for the right hand): https://github.com/NeoSpark314/godot_oculus_quest_toolkit/tree/master/OQ_Toolkit/OQ_ARVRController/models3d
By default the option on the OQ_ARVRController should be to autoload the hand model. Are you using the current master branch from this repo?

Could you use `adb logcat -s godot:* GodotOVRMobile:*` on a console to check if there is maybe an error that could give a hint on why the hand model is not loaded?

**Comment by Jiankors** [comment]
OK, since the quest is not available at the moment, i will check tomorrow and let you know later.
THX.

**Comment by NeoSpark314** [comment]
If you want you can also contact me on Discord next time you try: NeoSpark314#4701; If I'm at a computer at the same time it might be easier to debug this issue via direct chat.

**Comment by Jiankors** [comment]
hi, i hava tried adb logcat -s godot:* GodotOVRMobile:* on a console . and got an error. 

adb server version (31) doesn't match this client (41); killing...
* daemon started successfully
--------- beginning of system
--------- beginning of main
04-28 10:22:40.204  2344  2367 E godot   :    At: scene/3d/skeleton.cpp:328:_notification() - Condition "bone_index >= (uint32_t)len" is true. Continuing.
04-28 10:22:40.204  2344  2367 E godot   : ERROR: Condition "bone_index >= (uint32_t)len" is true. Continuing.

THX

**Comment by Jiankors** [comment]
i change the assets from master to v0.2 release version, and the problem was solved. THX.

**Comment by NeoSpark314** [comment]
Thank you for the update. Great that it works for you now; I will try to figure out if something is broken in master (the hand models should have been the same in v0.2 and current master; but maybe something else changed). cu around
