### ISSUE TITLE
Vive (OpenVR) compatibility saber angle

### ISSUE THREAD

**Issue by goatchurchprime** [NeoSpark314/godot_oculus_quest_toolkit#25]
I got it working!  This is a miracle of cross-platform compatibility.  

Needs a debug warning to install the "Open-VR" plugin if no devices are found and you have one plugged in.  This is blocked me for about an hour till I found it out.  (I didn't give up because I remembered it worked on another project.)

The controllers are a the wrong angle for playing Beep Saber -- they poke up instead of outwards.  I succeeded in playing by holding the controllers upside down.

**Comment by NeoSpark314** [comment]
Thanks for trying it. Not sure how cross device controller angle should be solved. Any suggestion on what to try is welcome. This is also an issue between hand-tracking and touch contorllers on the quest. Currently I have some controller "attachment" transforms as part of the respective models; maybe these can be modified based on a lookup table for different controller names.

**Comment by NeoSpark314** [comment]
@goatchurchprime I just fixed this in the master branch; thx again for reporting. Also I created a new repository for a stand-alone version of beep saber at https://github.com/NeoSpark314/BeepSaber
this allows to keep the demo in here as a small demo and start adding more features to the stand-alone version
