### ISSUE TITLE
Debug foot mesh in the collision shape capsule

### ISSUE THREAD

**Issue by goatchurchprime** [NeoSpark314/godot_oculus_quest_toolkit#27]
The physics interaction (standing and falling) is with a thing that is completely invisible.  

On the godot xr tools I was able to put squashed cylinder mesh into Function_Direct_movement -> KinematicBody to represent my foot on the ground, which is useful for debugging.  

When I put an object into the Feature_PlayerCollision it is fixed relative to the playing area origin instead of to the player position.

**Comment by NeoSpark314** [comment]
It depends on what you consider player position and what you want to visualize. You can activate Debug -> Visible Collision Shapes to see all collision shapes:
![image](https://user-images.githubusercontent.com/1610621/82894856-9179c500-9f53-11ea-8b76-dd0bfa7b4d4e.png)

You will need to attach shapes as child of the camera as this is the actual player position.

Falling/standing is implemented via ray casts so there is no direct way to visualize them without writing some code at the moment.

you can use the `vr.show_dbg_info("name", "value")` to debug values inside a running project.

**Comment by NeoSpark314** [comment]
Did you have a look into the option of visible collision shapes or debugging via log value (or positioning your debug object via code to the correct position)?

**Comment by goatchurchprime** [comment]
Afraid my VR kit has been taken back by its owner, so I've got to source my own at some point.  Will try visible collision shapes asap, but have no doubt that it will be good and should probably be mentioned early in the godot tutorials (I'll check).

I guess this is more of a question of the self-avatar feature (if that's what it is called).  Some games give you more than just the controllers, and there may be a case to putting it in the library, but it's not for me to decide.
