### ISSUE TITLE
Standing on object you are holding sends you into space

### ISSUE THREAD

**Issue by goatchurchprime** [NeoSpark314/godot_oculus_quest_toolkit#28]
I had step offset set to 0.4 and when I held the object I was holding towards my body space it assumed I was standing on it, and so moved me up, then it moved up the object I was holding, and repeated this until I was high in space.

**Comment by NeoSpark314** [comment]
If you want to avoid collision with objects you will need to setup the proper collision layers and masks to fit your gameplay logic. You can find some documentation on layers and masks here: https://docs.godotengine.org/en/stable/tutorials/physics/physics_introduction.html

**Comment by goatchurchprime** [comment]
How does this help?  Don't you want to collide with with same objects that you can pick up?

**Comment by NeoSpark314** [comment]
In the general case no. You want the falling feature only to collide with your level geometry. This is common practice for (simple) game collision. You usually setup your (named collision) layers to have finegrained control over what collides with what.

Of course if you want to implement a fully physics based game like boneworks this is different but then you will need to implement a very different and much more complex system than what the toolkit can provide.

**Comment by NeoSpark314** [comment]
Closing this for now. This is more of a problem related to the game and physics system that someone implements and not something that can be solved in a general way in the toolkit. Using collision layers and setting them according to the desired gameplay logic is one potential solution. Maybe there is a way to setup better default behavior; if someone has an idea let me know.
