### ISSUE TITLE
Type mismatch in OQ_UI2DLabel.gd

### ISSUE THREAD

**Issue by knochenhans** [NeoSpark314/godot_oculus_quest_toolkit#31]
Hi, when running the demo scene in Godot 3.2.2 beta 3, the debugger complained about [this](https://github.com/NeoSpark314/godot_oculus_quest_toolkit/blob/9d1775fdc19a8539148f3182ded8371ad7249234/OQ_Toolkit/OQ_UI2D/scripts/OQ_UI2DLabel.gd#L25) line with a mismatch between CenterContainer and ColorRect. Weird this didn’t came up when running the demo in Godot 3.2.1 before.

**Comment by NeoSpark314** [comment]
Ups; thank you for reporting this! I will fix it in a moment. It's indeed strange that this error does not pop up every time (I can run the demo fine...).
