### ISSUE TITLE
Instance name typo in vr_autoload.gd

### ISSUE THREAD

**Issue by knochenhans** [NeoSpark314/godot_oculus_quest_toolkit#32]
Hi, sifting through the code, I stumbled over a minor typo in vr_autoload.gd, beginning [here](https://github.com/NeoSpark314/godot_oculus_quest_toolkit/blob/b685abb4eeb4a2cbe5538c2fd99aac8c48e1c087/OQ_Toolkit/vr_autoload.gd#L297), should be ovrPerformance, not ovrPerfromance ;)

**Comment by NeoSpark314** [comment]
fixed it now; thanks!
