### ISSUE TITLE
gltf files linking to missing png files

### ISSUE THREAD

**Issue by knochenhans** [NeoSpark314/godot_oculus_quest_toolkit#33]
Hi, some of the gltf files in OQ_Toolkit/OQ_ARVRController/models3d contain links to texture files that do not exist in the tree:

- OculusQuestTouchControllerTexture.png (OculusQuestTouchController_Left.gltf and OculusQuestTouchController_Right.gltf)
- OculusQuestHandTexture_Color.png (OculusQuestHand_Left.gltf and OculusQuestHand_Right.gltf)

**Comment by NeoSpark314** [comment]
Yes; I think this is a sideeffect of editing the imported materials. If you want to use them in an external project with godot you will need to also copy the controllerMTL.material (which contains the correct texture reference for godot) as well as the two HandMaterial[Left/Right].material.

**Comment by NeoSpark314** [comment]
ah; and also take all the .import files with you (or configure the .gltf import to use an external material and not overwrite on re-import)

**Comment by knochenhans** [comment]
Ok thanks, I was just mentioning it because Godot was complaining about it when I imported the demo project :)

**Comment by NeoSpark314** [comment]
oh; thx; I did not realize that this is an actual error when opening a clean project. In that case I will try to reproduce this on my side and will try to fix it
