### ISSUE TITLE
Update the OVRMobile addon

### ISSUE THREAD

**Issue by knochenhans** [NeoSpark314/godot_oculus_quest_toolkit#34]
Hi, seems the OVRMobile addon is not up to date any more, as the recent version contains more functions (like vibrate_controller etc). Would be nice to update it.

Added to that, there’s Godot’s upcoming switch to the newer [Android plugin system](https://docs.godotengine.org/en/stable/tutorials/plugins/android/android_plugin.html) that might be worth a look for making the toolkit future proof, as the GodotVR driver already is compatible.

**Comment by NeoSpark314** [comment]
You should be able to use the new addon without any changes to the toolkit. That a precompiled addon is contained in the toolkit is just a convenience and I think it will be removed in the future.

The vibrate_controller is already covered by the ARVRController api to set the vibration so the additional API is not needed. Updating will not be that easy at the moment as for example the Mixed Reality Capture feature first needs to be ported to the new C++ OVRMobile addon.

**Comment by knochenhans** [comment]
Thanks for clearing that up!
