### ISSUE TITLE
The identifier "vr" isn't declared in the current scope

### ISSUE THREAD

**Issue by Lucaspec72** [NeoSpark314/godot_oculus_quest_toolkit#37]
I'm sure i'm just using it wrong but what did i mess up ? while i'm here i might as well also ask, how much of the toolkit is actually needed and what is just demos (what do i need to keep to have a clean project)

**Comment by NeoSpark314** [comment]
You need to add an autoload to your project (in the project settings); select the vr_autoload.gd file and name it vr for the toolkit to work. See step 4 here: https://github.com/NeoSpark314/godot_oculus_quest_toolkit/wiki/Tutorial-02-Basic-Project

The actual toolkit is in the OQ_Toolkit subfolder; the rest of the folders are not necessary to use the toolkit but depending on your setup could be convenient to keep as else you need them from a different source (for example bin contains the export templates; the addon folder contains the oculus mobile plugin and the demo_scenes and demo_games folder contain what the name implies)

**Comment by Lucaspec72** [comment]
oh ok thanks

**Comment by NeoSpark314** [comment]
no problem; feel free to open another issue if you run into problems; if you have questions along the way you could also join the godot discord #xr channel as there it is quite eqasy to discuss things.
