### ISSUE TITLE
Unable to activate hand tracking gesture detection

### ISSUE THREAD

**Issue by xuv** [NeoSpark314/godot_oculus_quest_toolkit#4]
First, let me thank you for putting this repo together. This is truly inspiring and extremely useful.

I'm trying to get the Demos running. And with the `HandTrackingDemoScene`, I can only see a black label telling me "Please enable hand tracking for gesture detection!".

I've looked around in different Godot project properties and the documentation you have for this project. But I can't seem to find how to activate this. Is there something I'm missing?

Godot Version: 3.2 beta5

**Comment by NeoSpark314** [comment]
You need to enable hand tracking in the settings of your Oculus Quest. Then it will switch to the tracked hands also inside the demo (no need to quit the application; it should work if you just resume it after enabling hand tracking)

![image](https://user-images.githubusercontent.com/1610621/71768238-a4dcb300-2f14-11ea-8266-192ca8076604.png)

**Comment by xuv** [comment]
OMG, of course. Why didn't I think to look in the Oculus settings. 
This feature is still a little too new. :)

Thanks a lot for this.
