### ISSUE TITLE
"set_foveation_level" function doesn't seem to work

### ISSUE THREAD

**Issue by Firepal** [NeoSpark314/godot_oculus_quest_toolkit#42]
Wasn't able to get it to work, no matter if ran before or after `initialize` in my root node script. The FFR won't change.
(i'm using GLES3 if that matters)

**Comment by Firepal** [comment]
false alert, it works. i just didn't set it to a high-enough level to be noticable (which is kind of a good thing)

**Comment by NeoSpark314** [comment]
Good to hear that it works :-); During development it is also a good idea to use the OVR metrics tool from oculus; It will show not only performance but also what foveation level is set: 
https://developer.oculus.com/blog/ovr-metrics-tool-vrapi-what-do-these-metrics-mean/
https://developer.oculus.com/documentation/tools/tools-ovrmetricstool/
For monitoring rendering performance and impact of changes this is a very valuable tool.

**Comment by NeoSpark314** [comment]
Ah; and in general using GLES3 is not reccomended as there are several problems with performance in the GLES3 pipeline; if possible you should switch to GLES2 to get the best performance.

**Comment by Firepal** [comment]
Thank you for your advice! I'll check out the OVR Metrics tool when I can.

Also, I was using GLES3 because shaders worked better with it (i had intense visual artifacts in the Quest with GLES2) but in retrospect I might want to cut back on that
