### ISSUE TITLE
Problem loading .dat map file on BeepSaber demo

### ISSUE THREAD

**Issue by zweihander11** [NeoSpark314/godot_oculus_quest_toolkit#43]
Hello
I recently just got a Quest2 and managed to install and run this kit perfectly. I love it!
The BeepSaber demo runs fine on PC but when sideloaded to the Quest everything works except that I'm unable to start the game. I get the Error saying the Json file can't be loaded from the .dat

Any ideas why this might be? Any hint would be appreciated.

I'm using Godot 3.2.1 and created a new project  using only the Beep Saber folder and got the plugin from this repo (not the Godot Asset Library). I had to fix a lot of dependencies manually so maybe I missed something there.
I already checked whether the file exists on the device and messed with files directory to ensure proper access but still no clue.
I'm thinking it has something to do with the manifest but I'm not sure, plus I'm not expert in Android Manifest.

Thank you for sharing and any help you can provide

**Comment by NeoSpark314** [comment]
Does it work for you when you launch the full project from the repository without modifications on your Quest?

**Comment by zweihander11** [comment]
As a matter of fact it does work perfectly if I run the full project. Thanks, that never occurred to me hahaha
For the time being I would just like to build my own map and tune but eventually I would like to add new features such as notes coming from all directions or whatever. So it would be nice to have it as a separate project.
I guess the problem was broken dependencies.

**Comment by NeoSpark314** [comment]
Making improvements in a separate project sounds like a great idea; some time ago there was already a contribution that added multiple different songs; they are currently in this branch (https://github.com/NeoSpark314/godot_oculus_quest_toolkit/tree/beepsaber) as I did not manage yet to merge tham into master; but maybe keeping the demo as it is and making improvements in a new project would be better and could also get probably more people interested in contributing.

**Comment by zweihander11** [comment]
Thank you that sounds great. I will try to fix the dependencies problem and contribute if possible. I still have no clue on how to solve that. I'm no expert so I might ask for help again.

**Comment by NeoSpark314** [comment]
Hi @zweihander11 
I created now a stand alone version at https://github.com/NeoSpark314/BeepSaber; it should work out of the box; if not please let me know. Also feel free to ask if you run into problems; you can also reach me on discord if you want (either in the official godot #xr channel at https://discord.gg/NX4uC9E or NeoSpark314#4701)

cheers

**Comment by zweihander11** [comment]
Thank you very much that's amazing. It works perfect.
It's very useful to be able to read and learn from the source so I'd be happy to contribute with improvements eventually.

**Comment by zweihander11** [comment]
Hello again, I managed to track down this issue. In the end the problem was on the export settings, you need to specify the filter for non-resource files folder so the Oculus Quest can find them. It's useful if you want to use the vr.load_json_file() function included in the toolkit. So perhaps it's worth adding it to the documentation.
![Screenshot from 2020-11-08 14-18-32]

(https://user-images.githubusercontent.com/17891608/98457698-716e5300-21cd-11eb-98ec-8181db7a5be6.png)

**Comment by NeoSpark314** [comment]
Thanks; yes; it is a good idea to document this; I added a comment above the function describing on how to use it with .json files that are part of the project structure: https://github.com/NeoSpark314/godot_oculus_quest_toolkit/pull/44/commits/348350af28d99d8549119e9801724f0b4e4200b5
