### ISSUE TITLE
About featuring 

### ISSUE THREAD

**Issue by zweihander11** [NeoSpark314/godot_oculus_quest_toolkit#55]
Hello again. So far I've been using the toolkit for small personal projects mainly for experiment purpose and learning.
However I recently published a small project on sidequest and I was wondering if it could be added here on the feature projects section. 

https://sidequestvr.com/app/2519

Any help will be of course greatly appreciated

**Comment by NeoSpark314** [comment]
This looks really cool. And as far as I know it is the first commercial project using the toolkit :-); I will add it to the list of showcases. Do you plan to submit it also to the new Oculus Applab?

**Comment by zweihander11** [comment]
That would be very helpful. I have no plans to submit to Applab just yet as they have a lot of filters and to be honest this is still a work in progress. That is one of the cool things about sidequest: it's a platform more open to trial and error.
At the moment I just want to see how it goes and keep improving. 
Thanks a lot for the support and specially for sharing and maintaining the toolkit. It makes everything so simple and easy inside Godot, even better than Unity I think.
Please let me know if I can be of any help too.

**Comment by NeoSpark314** [comment]
Now it is added to the README.md on the front page of the toolkit. 
I also created a discord specific for users of the toolkit. If you want you can join here: https://discord.gg/JtTpFk9852 
I hope that it makes asking questions and solving problems specific to the toolkit easier.
