### ISSUE TITLE
Feature_UIRayCast references non-member variable vr.ovrHandTracking  

### ISSUE THREAD

**Issue by goatchurchprime** [NeoSpark314/godot_oculus_quest_toolkit#57]
This line: https://github.com/NeoSpark314/godot_oculus_quest_toolkit/blob/master/OQ_Toolkit/OQ_ARVRController/scripts/Feature_UIRayCast.gd#L30
`if (vr.ovrHandTracking):`

causes an error because ovrHandTracking is not listed anywhere in 
https://github.com/NeoSpark314/godot_oculus_quest_toolkit/blob/master/OQ_Toolkit/vr_autoload.gd

It's not obvious what it is supposed to be, or if there is a huge block of code missing.

**Comment by NeoSpark314** [comment]
thanks for finding this; this functionality was moved in some recent refactoring and I forgot this code location. I'll fix it

**Comment by goatchurchprime** [comment]
When this works I'll extend https://github.com/goatchurchprime/OQ_Networking_Demo to handing the hand-tracking, which is always pretty compelling.  It's a pretty neat demo when you can network in on someone's desktop screen running a flat WebXR version with your hand-tracking all working.  I can pack all the transforms down as Vector3s so they don't take so much bandwidth.

**Comment by NeoSpark314** [comment]
should be fixed now on master
