### ISSUE TITLE
ovrUtilities.is_oculus_quest_1_device does not exist

### ISSUE THREAD

**Issue by goatchurchprime** [NeoSpark314/godot_oculus_quest_toolkit#59]
I had to comment out the two lines at startup in vr_autoload that do the following logging:

```
	log_info(str("      is_oculus_quest_1_device: ", is_oculus_quest_1_device()));
	log_info(str("      is_oculus_quest_2_device: ", is_oculus_quest_2_device()));
```

This looks like it could be an updated function in a more recent version of the godot_ovrmobile addon asset than comes in the AssetLib (v 3.0.1)?  Have I got that right?

I prefer not to commit that binary libraries into my source code repo.  Is there a way to read the version of the library that's loaded and give an warning that it is less than what your toolkit expects?

**Comment by NeoSpark314** [comment]
yes; there is a gap between the official oculus mobile plugin and what is supported in the toolkit; the toolkit is based on a branch (you can find it here: https://github.com/NeoSpark314/godot_oculus_mobile). One of the reasons for the branch is that the Mixed Reality Capture support is not yet ported into the official oculus mobile plugin. So there are some differences on the API and which functions are exported.

**Comment by goatchurchprime** [comment]
There's a really huge difference between these versions.  I copied the addons/ovr_mobile file across as you can see...

![image](https://user-images.githubusercontent.com/677254/111314503-620a8500-8659-11eb-947f-d0d30fd335e2.png)

![image](https://user-images.githubusercontent.com/677254/111314586-73539180-8659-11eb-83f2-8077d1f7042f.png)

Now that I deleted the backup Dgodot_ovrmobile directory it worked (I'm after the hand-tracking).

What is the right thing to do?  I originally had the OQ_Toolkit not in my repo, but then my project wouldn't open when it's not AssetLib imported in, so I copied across just that directory of source code files.  I've not been able to see the best way to handle these dependencies.  

Given how easy it is to get into this pickle, at the very least we need some detection and warning about what needs to be fixed.  Maybe an error message if the expected functions are not in the library telling us where to get it from for the time being.

**Comment by NeoSpark314** [comment]
currently the best thing to do is to use the ovrmobile version that is part of the OQ_Toolkit here on this repository https://github.com/NeoSpark314/godot_oculus_quest_toolkit/tree/master/addons/godot_ovrmobile; this is what I test with when developing

For the assetlib I'm not sure but I hope it also just includes the correct version of the ovrmobile from this repo here but I need to check this...

**Comment by NeoSpark314** [comment]
Adding a check is a good idea; I will add something like this and log it as an error
