### ISSUE TITLE
The method of is_oculus_quest_2_device returns false in Oculus Quest 2

### ISSUE THREAD

**Issue by jtakakura** [NeoSpark314/godot_oculus_quest_toolkit#68]
In my Oculus Quest 2, is_oculus_quest_2_device() method returns false and is_oculus_quest_1_device() returns true.
Maybe it needs to modify the AndroidManifest.xml to detect the correct device type of Oculus Quest 2.

**Comment by NeoSpark314** [comment]
Should be fixed with 28b994eb4f3c2c47a3fe1cc76ce9e2ea78503769; new manifest is included; but I have no Quest 2 to verify. So please reopen in case it is not solved.
