### ISSUE TITLE
static grab feature does not move object

### ISSUE THREAD

**Issue by DerKorb** [NeoSpark314/godot_oculus_quest_toolkit#7]
Either I am not understanding this feature right or you forgot to apply delta_position to the grabbed object after you calculate it.

**Comment by NeoSpark314** [comment]
static_grab in its current implementation does nothing by itself but is intended to be used in combination with other code/features. It is used for example in the climbing mechanic; it basically just computes the delta_position and you can do with it what you need to.

**Comment by DerKorb** [comment]
Ah, I thought it could be used to grab static items.

**Comment by NeoSpark314** [comment]
hmm; yes; not a very good name choice from my side... and also not yet documented...; currently there is only the rigid body grab functionality (with several options on how the grab works there); But having something to just grab non rigid body objects would indeed be useful. I think how I could add this in a future update. Feel free to contact me anytime you run into problems or have questions; you can reach me also on discord: NeoSpark314#4701
Cheers.
