### ISSUE TITLE
Post grabbing a object the collision object does not collide any more 

### ISSUE THREAD

**Issue by ronghester** [NeoSpark314/godot_oculus_quest_toolkit#70]
Hi, (This is discussion not a issue)

Just playing around with library and i wanted to know how can i make the object collide with other object after gabbing it by controller ? Take for example the table tennis bat when we throw it in the scene it collides with other object but when it is grabbed it does not collide at all. 

Please suggest. (tried a demo game & files but did not find any thing). 

Thanks

**Comment by NeoSpark314** [comment]
Did you try the PhysicsScene.tscn demo scene? There the cubes collide. And there are also different grab modes as examples that have different behaviour in combination with the physics engine.

**Comment by ronghester** [comment]
Unfortunately the physicsscene.tscn does not work for me.  When i run the project with that scene there is continuous loading symbol in device.  No errors in console ( I am on oculus quest 2 & GoDot 3.2.3)

However i checked the physics scene and there are bunch of rigid bodies all extending a OQ_GrabbledRigidBody .. My observation is that this body when grabbed does not collide with anything else in the scene. 

Any pointers ?

**Comment by NeoSpark314** [comment]
Can you try the full included demo project directly (when downloading this repo)? This should all work out of the box and you can select the demo scenes in the main menu.

**Comment by ronghester** [comment]
Tried the full included demo project (by importing project into Godot) and physics scene works. That is exactly what I was looking for. The setup looks simple but on trying to replicate the same setting in test project the controller is not able to grab the rigid bodies. Will try to play around with the Physics Scene and see if I can figure it out myself. 

This is how the setup looks like
OQ_LeftController 

- Feature_RigidBodyGrab (Grab_Type: hingeJoint) 

OQ_RightController
-Feature_RigidBodyGrab (Grab_Type : Velocity & Reparent Mesh : True) 

Bunch of Rigid Body in the scene 
OQClass_GrabbledRigidBody 

- CollisionShape
- Mesh

**Comment by ronghester** [comment]
This was a configuration problem; it is resolved now. 
Thank
