### ISSUE TITLE
OpenXR support

### ISSUE THREAD

**Issue by MrEliptik** [NeoSpark314/godot_oculus_quest_toolkit#76]
Hey, I've been using your toolkit for a while now, and I first want to thank you a lot for your work. It's my go-to plugin when creating a new project and some of the features are absolute life savers. 

I understand that Godot is moving to OpenXR and that the VRApi support is going to end during 2022. I'd love to move to OpenXR but I'm worried it will break compatibility with this addon. Can you tell me if you already support OpenXR? If yes, what steps should I take to replace the VRApi? And if not, do you think it's possible?

**Comment by NeoSpark314** [comment]
Thanks for the feedback. So far I have not looked into the OpenXR support of Godot but most of the toolkit code is not using platform specifics and thus should work also with the OpenXR plugin. I used parts of the functionality of the toolkit already with OpenVR and also WebXR and the initialization code for these platforms is included in the vr_autoload.

Your main entry point if you want to give it a try is to add the initialization of OpenXR here using the other platforms that are initialized there as a reference: https://github.com/NeoSpark314/godot_oculus_quest_toolkit/blob/51fe3b7ccf0c4f5d41e0b375b5b5aa18e3812799/OQ_Toolkit/vr_autoload.gd#L858

What will not work out of the box that I can think of is hand tracking support and guardian access. This will require some deeper code changes and additions.

**Comment by MrEliptik** [comment]
Thanks a lot for your answer! I'll give OpenXR a go and then I'll see if I can integrate it into this addon.

**Comment by NeoSpark314** [comment]
Basic detection/initialization was added in 3fd9aa3a95483ab260b1694cc5ebe474573bbf10; but many features are not yet implemented/supported when using OpenXR
