### ISSUE TITLE
Imported FBX models don't show up in VR, but they do show up everywhere else

### ISSUE THREAD

**Issue by nightblade9** [NeoSpark314/godot_oculus_quest_toolkit#77]
3D dev noob here. Sorry if this is something obvious (flipped normals?) but I can't figure it out.

I created a new project/scene with a fork of one of the others (BeatSaber, I think) and imported three different FBX models; one of them is this apple one from TurboSquid: https://www.turbosquid.com/3d-models/apple-cartoon-3d-1495154.

I created a new scene by right-clicking, picking "new inherited scene," and I can verify that the mesh appears normally. I save an instance, go to my game scene, and add the newly-saved instance; it shows up correctly.

The really puzzling thing: if I run the regular (Windows) target/debugger, the mesh appears fine. But, if I deploy and run to Oculus, the mesh is simply missing.

Things I tried:

- Three different meshes
- Removing any/all materials
- Scaling fruits up and down in size

Two things that worked:

- Importing the castle mesh from one of the other scenes; it appears fine.
- Adding a MeshInstance to one of my imported-and-saved scenes; that part of the mesh shows up fine.

What am I missing / doing wrong?

**Comment by NeoSpark314** [comment]
Hi,

which Godot version are you using? From what you describe it is probably a duplicate of #74. With Godot >= 3.4 something has changed with how meshes are import and the included binaries in the toolkit are not yet updated. Can you try with godot 3.3 (and make sure to re-import your meshes by deleting the .import folder before opening the project).

**Comment by nightblade9** [comment]
You're right - I was using 3.4. I didn't notice the controller meshes were missing - I'll try to remember that for next time.

Deleting `.import` wasn't enough, I had to re-import the FBX files (create a new inherited scene from the FBX file). After that, it works. 

Closing since this is a dupe of #74. Thanks for the help!
